# Local PostgreSQL Configuration
# Uses local PostgreSQL database instead of Railway

# Server Configuration
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market_mind
    username: tdk928
    password: tdk55
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          charSet: UTF-8
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: company-manager

# Logging Configuration
logging:
  level:
    companymanager: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
