# Server Configuration
server:
  port: 8080

# Database Configuration (PostgreSQL on Railway)
spring:
  datasource:
    url: jdbc:postgresql://<host>:<port>/<database>
    username: <username>
    password: <password>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: company-manager

# Logging Configuration
logging:
  level:
    companymanager: DEBUG
    org.springframework.web: DEBUG 