# Server Configuration
server:
  port: 8080

# Database Configuration (H2 in-memory database)
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Application Name
  application:
    name: company-manager

# Logging Configuration
logging:
  level:
    com.company.companymanager: DEBUG
    org.springframework.web: DEBUG 