# Server Configuration
server:
  port: 8080

# Database Configuration (Docker PostgreSQL - Railway compatible)
spring:
  datasource:
    url: jdbc:postgresql://localhost:19210/market_mind
    username: tdk
    password: tdk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: company-manager

# Logging Configuration
logging:
  level:
    companymanager: DEBUG
    org.springframework.web: DEBUG 